import { ContractRoute } from './types';

export const contractRoutes: ContractRoute[] = [
  {
    id: 'dashboard-overview',
    method: 'GET',
    path: '/dashboard/overview',
    operationId: 'getDashboardOverview',
    page: 'terminal/dashboard',
    feature: 'KPI cards',
    status: 'available',
  },
  {
    id: 'dashboard-equity',
    method: 'GET',
    path: '/dashboard/equity-series',
    operationId: 'getDashboardEquitySeries',
    page: 'terminal/dashboard',
    feature: 'Equity chart',
    status: 'available',
  },
  {
    id: 'dashboard-allocation',
    method: 'GET',
    path: '/dashboard/exchange-allocation',
    operationId: 'getExchangeAllocation',
    page: 'terminal/dashboard',
    feature: 'Exchange allocation donut',
    status: 'available',
  },
  {
    id: 'bots-list',
    method: 'GET',
    path: '/bots',
    operationId: 'listPublicBotsWithFilters',
    page: 'terminal/marketplace',
    feature: 'Marketplace bot feed',
    status: 'available',
  },
  {
    id: 'bot-register',
    method: 'POST',
    path: '/bots',
    operationId: 'registerBot',
    page: 'terminal/create-bot',
    feature: 'Create bot and receive apiKey + rawSecret',
    status: 'available',
  },
  {
    id: 'bot-signal-submit',
    method: 'POST',
    path: '/signals',
    operationId: 'submitSignal',
    page: 'terminal/create-bot',
    feature: 'Runtime communication channel using bot secret',
    status: 'available',
  },
  {
    id: 'strategy-detail',
    method: 'GET',
    path: '/strategies/{strategyId}',
    operationId: 'getStrategyDetail',
    page: 'terminal/strategies',
    feature: 'Strategy hero metadata',
    status: 'available',
  },
  {
    id: 'strategy-metrics',
    method: 'GET',
    path: '/strategies/{strategyId}/metrics',
    operationId: 'getStrategyMetrics',
    page: 'terminal/strategies',
    feature: 'Performance metrics cards',
    status: 'available',
  },
  {
    id: 'strategy-series',
    method: 'GET',
    path: '/strategies/{strategyId}/performance-series',
    operationId: 'getStrategyPerformanceSeries',
    page: 'terminal/strategies',
    feature: 'Performance chart',
    status: 'available',
  },
  {
    id: 'strategy-trades',
    method: 'GET',
    path: '/strategies/{strategyId}/trades',
    operationId: 'listStrategyTradeLogs',
    page: 'terminal/strategies',
    feature: 'Trade log table',
    status: 'available',
  },
  {
    id: 'paper-session',
    method: 'GET',
    path: '/paper/session',
    operationId: 'getPaperSessionSummary',
    page: 'terminal/paper-trading',
    feature: 'Session headline metrics',
    status: 'available',
  },
  {
    id: 'paper-signals',
    method: 'GET',
    path: '/paper/signals',
    operationId: 'listPaperSignals',
    page: 'terminal/paper-trading',
    feature: 'Signal terminal feed',
    status: 'available',
  },
  {
    id: 'paper-order',
    method: 'POST',
    path: '/paper/orders',
    operationId: 'createPaperOrder',
    page: 'terminal/paper-trading',
    feature: 'Quick order form',
    status: 'available',
  },
  {
    id: 'profile-me',
    method: 'GET',
    path: '/users/me',
    operationId: 'getCurrentUserProfile',
    page: 'terminal/profile',
    feature: 'User profile card',
    status: 'available',
  },
  {
    id: 'profile-api-keys',
    method: 'GET',
    path: '/users/me/api-keys',
    operationId: 'listApiKeys',
    page: 'terminal/profile',
    feature: 'API key vault',
    status: 'available',
  },
  {
    id: 'system-signals',
    method: 'GET',
    path: '/signals',
    operationId: 'listSignals',
    page: 'terminal/developer-console',
    feature: 'Signal stream',
    status: 'available',
  },
  {
    id: 'leaderboard-list',
    method: 'GET',
    path: '/leaderboard/strategies',
    operationId: 'listLeaderboardStrategies',
    page: 'market, terminal/leaderboard',
    feature: 'Leaderboard ranking table',
    status: 'available',
  },
  {
    id: 'leaderboard-featured',
    method: 'GET',
    path: '/leaderboard/featured',
    operationId: 'listLeaderboardFeatured',
    page: 'market, terminal/leaderboard',
    feature: 'Featured cards',
    status: 'available',
  },
  {
    id: 'academy-courses',
    method: 'GET',
    path: '/academy/courses',
    operationId: 'listAcademyCourses',
    page: 'training',
    feature: 'Course cards and progress',
    status: 'gap',
    notes: 'Required for training landing without hardcoded modules.',
  },
  {
    id: 'academy-metrics',
    method: 'GET',
    path: '/academy/metrics',
    operationId: 'getAcademyMetrics',
    page: 'training',
    feature: 'Academy KPI strip',
    status: 'gap',
  },
  {
    id: 'content-blog',
    method: 'GET',
    path: '/content/blog/posts',
    operationId: 'listBlogPosts',
    page: 'blog',
    feature: 'Blog feed and category filters',
    status: 'gap',
  },
  {
    id: 'content-research',
    method: 'GET',
    path: '/content/research/reports',
    operationId: 'listResearchReports',
    page: 'research',
    feature: 'Research cards and PDF library',
    status: 'gap',
  },
  {
    id: 'market-hero-stats',
    method: 'GET',
    path: '/market/overview',
    operationId: 'getMarketOverview',
    page: 'home, market',
    feature: 'Top volume and market pulse',
    status: 'gap',
  },
];

export const availableContracts = contractRoutes.filter((route) => route.status === 'available');

export const missingContracts = contractRoutes.filter((route) => route.status === 'gap');
