import { ContractRoute } from './types';

export const contractRoutes: ContractRoute[] = [
  {
    id: 'dashboard-overview',
    method: 'GET',
    path: '/dashboard/overview',
    operationId: 'getDashboardOverview',
    page: 'terminal/dashboard',
    feature: 'KPI cards',
    status: 'available',
  },
  {
    id: 'dashboard-equity',
    method: 'GET',
    path: '/dashboard/equity-series',
    operationId: 'getDashboardEquitySeries',
    page: 'terminal/dashboard',
    feature: 'Equity chart',
    status: 'available',
  },
  {
    id: 'dashboard-allocation',
    method: 'GET',
    path: '/dashboard/exchange-allocation',
    operationId: 'getExchangeAllocation',
    page: 'terminal/dashboard',
    feature: 'Exchange allocation donut',
    status: 'available',
  },
  {
    id: 'dashboard-trades',
    method: 'GET',
    path: '/dashboard/trades',
    operationId: 'getDashboardTrades',
    page: 'terminal/dashboard',
    feature: 'Dashboard all user trades list',
    status: 'available',
  },
  {
    id: 'bots-list',
    method: 'GET',
    path: '/bots',
    operationId: 'listPublicBotsWithFilters',
    page: 'terminal/marketplace',
    feature: 'Marketplace bot feed',
    status: 'available',
  },
  {
    id: 'bot-register',
    method: 'POST',
    path: '/bots/register',
    operationId: 'registerBot',
    page: 'terminal/create-bot',
    feature: 'Create bot and receive apiKey + rawSecret',
    status: 'available',
  },
  {
    id: 'bot-detail',
    method: 'GET',
    path: '/bots/{botId}',
    operationId: 'getBotDetail',
    page: 'terminal/marketplace',
    feature: 'Marketplace bot detail',
    status: 'available',
  },
  {
    id: 'bot-subscribe',
    method: 'POST',
    path: '/subscriptions/{botId}',
    operationId: 'subscribeToBot',
    page: 'terminal/marketplace',
    feature: 'Subscribe to a bot',
    status: 'available',
  },
  {
    id: 'bot-unsubscribe',
    method: 'DELETE',
    path: '/subscriptions/{botId}',
    operationId: 'unsubscribeFromBot',
    page: 'terminal/marketplace',
    feature: 'Unsubscribe from a bot',
    status: 'available',
  },
  {
    id: 'bot-signal-submit',
    method: 'POST',
    path: '/signals',
    operationId: 'submitSignal',
    page: 'terminal/create-bot',
    feature: 'Runtime communication channel using bot secret',
    status: 'available',
  },
  {
    id: 'bot-analytics-metrics',
    method: 'GET',
    path: '/bots/{botId}/analytics/metrics',
    operationId: 'getBotAnalyticsMetrics',
    page: 'terminal/bots/[botId]',
    feature: 'Bot-level OOS metric blocks',
    status: 'available',
  },
  {
    id: 'bot-analytics-series',
    method: 'GET',
    path: '/bots/{botId}/analytics/performance-series',
    operationId: 'getBotAnalyticsPerformanceSeries',
    page: 'terminal/bots/[botId]',
    feature: 'Bot-level OOS performance chart',
    status: 'available',
  },
  {
    id: 'bot-trades',
    method: 'GET',
    path: '/bots/{botId}/trades',
    operationId: 'listBotTrades',
    page: 'terminal/bots/[botId]',
    feature: 'Trade log table',
    status: 'available',
  },
  {
    id: 'profile-me',
    method: 'GET',
    path: '/users/me',
    operationId: 'getCurrentUserProfile',
    page: 'terminal/profile',
    feature: 'User profile card',
    status: 'available',
  },
  {
    id: 'profile-update',
    method: 'PUT',
    path: '/users/me',
    operationId: 'updateCurrentUserProfile',
    page: 'terminal/profile',
    feature: 'Update user profile',
    status: 'available',
  },
  {
    id: 'profile-password-update',
    method: 'PUT',
    path: '/users/me/password',
    operationId: 'changeCurrentUserPassword',
    page: 'terminal/profile',
    feature: 'Change user password',
    status: 'available',
  },
  {
    id: 'profile-preferences',
    method: 'GET',
    path: '/users/me/preferences',
    operationId: 'getCurrentUserPreferences',
    page: 'terminal/profile',
    feature: 'User preferences',
    status: 'available',
  },
  {
    id: 'profile-preferences-update',
    method: 'PUT',
    path: '/users/me/preferences',
    operationId: 'updateCurrentUserPreferences',
    page: 'terminal/profile',
    feature: 'Update user preferences',
    status: 'available',
  },
  {
    id: 'profile-api-key-create',
    method: 'POST',
    path: '/users/me/api-keys',
    operationId: 'createApiKey',
    page: 'terminal/profile',
    feature: 'Create API key',
    status: 'available',
  },
  {
    id: 'profile-api-key-delete',
    method: 'DELETE',
    path: '/users/me/api-keys/{apiKeyId}',
    operationId: 'deleteApiKey',
    page: 'terminal/profile',
    feature: 'Delete API key',
    status: 'available',
  },
  {
    id: 'profile-login-activities',
    method: 'GET',
    path: '/users/me/login-activities',
    operationId: 'listLoginActivities',
    page: 'terminal/profile',
    feature: 'Login activity history',
    status: 'available',
  },
  {
    id: 'profile-api-keys',
    method: 'GET',
    path: '/users/me/api-keys',
    operationId: 'listApiKeys',
    page: 'terminal/profile',
    feature: 'API key vault',
    status: 'available',
  },
  {
    id: 'system-signals',
    method: 'GET',
    path: '/signals',
    operationId: 'listSignals',
    page: 'terminal/developer-console',
    feature: 'Signal stream',
    status: 'available',
  },
  {
    id: 'system-connectivity',
    method: 'GET',
    path: '/system/connectivity',
    operationId: 'getSystemConnectivity',
    page: 'terminal/developer-console',
    feature: 'System connectivity health',
    status: 'available',
  },
  {
    id: 'system-execution-logs',
    method: 'GET',
    path: '/system/execution-logs',
    operationId: 'listExecutionLogs',
    page: 'terminal/developer-console',
    feature: 'Execution log stream',
    status: 'available',
  },
  {
    id: 'admin-dashboard',
    method: 'GET',
    path: '/admin/dashboard',
    operationId: 'getAdminDashboard',
    page: 'terminal/admin',
    feature: 'Admin dashboard',
    status: 'available',
  },
  {
    id: 'admin-users',
    method: 'GET',
    path: '/admin/users',
    operationId: 'listAdminUsers',
    page: 'terminal/admin/users',
    feature: 'Admin user table',
    status: 'available',
  },
  {
    id: 'admin-user-role-update',
    method: 'PATCH',
    path: '/admin/users/{userId}/role',
    operationId: 'updateAdminUserRole',
    page: 'terminal/admin/users',
    feature: 'Update user role',
    status: 'available',
  },
  {
    id: 'admin-user-ban-update',
    method: 'PATCH',
    path: '/admin/users/{userId}/ban',
    operationId: 'updateAdminUserBan',
    page: 'terminal/admin/users',
    feature: 'Ban or unban user',
    status: 'available',
  },
  {
    id: 'admin-bots',
    method: 'GET',
    path: '/admin/bots',
    operationId: 'listAdminBots',
    page: 'terminal/admin/bots',
    feature: 'Admin bot table',
    status: 'available',
  },
  {
    id: 'admin-bot-detail',
    method: 'GET',
    path: '/admin/bots/{botId}',
    operationId: 'getAdminBotDetail',
    page: 'terminal/admin/bots/[botId]',
    feature: 'Admin bot detail',
    status: 'available',
  },
  {
    id: 'admin-bot-status-update',
    method: 'PATCH',
    path: '/admin/bots/{botId}/status',
    operationId: 'updateAdminBotStatus',
    page: 'terminal/admin/bots/[botId]',
    feature: 'Update bot status',
    status: 'available',
  },
  {
    id: 'admin-bot-signals',
    method: 'GET',
    path: '/admin/bots/{botId}/signals',
    operationId: 'listAdminBotSignals',
    page: 'terminal/admin/bots/[botId]',
    feature: 'Bot signal audit',
    status: 'available',
  },
  {
    id: 'admin-bot-subscribers',
    method: 'GET',
    path: '/admin/bots/{botId}/subscribers',
    operationId: 'listAdminBotSubscribers',
    page: 'terminal/admin/bots/[botId]',
    feature: 'Bot subscriber list',
    status: 'available',
  },
  {
    id: 'admin-subscription-force-cancel',
    method: 'PATCH',
    path: '/admin/subscriptions/{userSubscriptionId}/force-cancel',
    operationId: 'forceCancelAdminSubscription',
    page: 'terminal/admin/bots/[botId]',
    feature: 'Force cancel subscription',
    status: 'available',
  },
  {
    id: 'admin-audit-events',
    method: 'GET',
    path: '/admin/audit-events',
    operationId: 'listAdminAuditEvents',
    page: 'terminal/admin',
    feature: 'Admin audit trail',
    status: 'available',
  },
  {
    id: 'admin-system-connectivity',
    method: 'GET',
    path: '/admin/system/connectivity',
    operationId: 'getAdminSystemConnectivity',
    page: 'terminal/admin/system',
    feature: 'Admin connectivity health',
    status: 'available',
  },
  {
    id: 'admin-system-execution-logs',
    method: 'GET',
    path: '/admin/system/execution-logs',
    operationId: 'listAdminExecutionLogs',
    page: 'terminal/admin/system',
    feature: 'Admin execution logs',
    status: 'available',
  },
  {
    id: 'leaderboard-list',
    method: 'GET',
    path: '/leaderboard/bots',
    operationId: 'listLeaderboardBots',
    page: 'market, terminal/leaderboard',
    feature: 'Leaderboard ranking table',
    status: 'available',
  },
  {
    id: 'leaderboard-featured',
    method: 'GET',
    path: '/leaderboard/featured',
    operationId: 'listLeaderboardFeatured',
    page: 'market, terminal/leaderboard',
    feature: 'Featured cards',
    status: 'available',
  },
  {
    id: 'marketing-stats',
    method: 'GET',
    path: '/public/marketing/stats',
    operationId: 'getMarketingStats',
    page: 'home',
    feature: 'Marketing trust indicators',
    status: 'available',
  },
  {
    id: 'academy-courses',
    method: 'GET',
    path: '/academy/courses',
    operationId: 'listAcademyCourses',
    page: 'training',
    feature: 'Course cards and progress',
    status: 'gap',
    notes: 'Required for training landing without hardcoded modules.',
  },
  {
    id: 'academy-metrics',
    method: 'GET',
    path: '/academy/metrics',
    operationId: 'getAcademyMetrics',
    page: 'training',
    feature: 'Academy KPI strip',
    status: 'gap',
  },
  {
    id: 'content-blog',
    method: 'GET',
    path: '/content/blog/posts',
    operationId: 'listBlogPosts',
    page: 'blog',
    feature: 'Blog feed and category filters',
    status: 'gap',
  },
  {
    id: 'content-research',
    method: 'GET',
    path: '/content/research/reports',
    operationId: 'listResearchReports',
    page: 'research',
    feature: 'Research cards and PDF library',
    status: 'gap',
  },
  {
    id: 'content-research-library',
    method: 'GET',
    path: '/content/research/reports/library',
    operationId: 'listResearchLibraryFiles',
    page: 'research',
    feature: 'Research library files',
    status: 'gap',
  },
  {
    id: 'market-hero-stats',
    method: 'GET',
    path: '/market/overview',
    operationId: 'getMarketOverview',
    page: 'home, market',
    feature: 'Top volume and market pulse',
    status: 'gap',
  },
  // ========== Developer Dashboard (MVP) ==========
  {
    id: 'developer-bots',
    method: 'GET',
    path: '/bots/my-bots',
    operationId: 'listDeveloperBots',
    page: 'terminal/developer-dashboard',
    feature: 'Developer bot registry',
    status: 'available',
  },
  {
    id: 'developer-bot-detail',
    method: 'GET',
    path: '/bots/{botId}',
    operationId: 'getBotDetail',
    page: 'terminal/developer-dashboard',
    feature: 'Developer bot detail',
    status: 'available',
  },
  {
    id: 'developer-bot-integration-health',
    method: 'GET',
    path: '/bots/{botId}/integration-health',
    operationId: 'getBotIntegrationHealth',
    page: 'terminal/developer-dashboard',
    feature: 'Bot integration health',
    status: 'available',
  },
  {
    id: 'developer-bot-subscriptions',
    method: 'GET',
    path: '/subscriptions/{botId}/active',
    operationId: 'listActiveSubscriptionsForBot',
    page: 'terminal/developer-dashboard',
    feature: 'Bot subscription list for developer',
    status: 'available',
  },
  {
    id: 'developer-bot-update-status',
    method: 'PATCH',
    path: '/bots/{botId}/status',
    operationId: 'updateBotStatus',
    page: 'terminal/developer-dashboard',
    feature: 'Update bot status (Active, Paused, Down, Deleted)',
    status: 'available',
  },
  {
    id: 'developer-bot-update-metadata',
    method: 'PATCH',
    path: '/bots/{botId}/metadata',
    operationId: 'updateBotMetadata',
    page: 'terminal/developer-dashboard',
    feature: 'Update bot metadata (name, description, pairs)',
    status: 'available',
  },
  {
    id: 'developer-bot-delete',
    method: 'DELETE',
    path: '/bots/{botId}',
    operationId: 'deleteBot',
    page: 'terminal/developer-dashboard',
    feature: 'Delete bot with subscriber checks',
    status: 'available',
  },
  // ========== Phase 1: Decision Dashboard ==========
  {
    id: 'portfolio-overview',
    method: 'GET',
    path: '/dashboard/portfolio/overview',
    operationId: 'getPortfolioOverview',
    page: 'terminal/decision',
    feature: 'Portfolio KPI cards',
    status: 'available',
  },
  {
    id: 'portfolio-decisions',
    method: 'GET',
    path: '/dashboard/portfolio/decisions',
    operationId: 'getPortfolioDecisions',
    page: 'terminal/decision',
    feature: 'Subscription decision cards with reason tags',
    status: 'available',
  },
];

export const availableContracts = contractRoutes.filter((route) => route.status === 'available');

export const missingContracts = contractRoutes.filter((route) => route.status === 'gap');
